server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://1.12.248.106:3308/learning-demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hex.549696136
