// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.luckykuang.common.user;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();
}
