// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.luckykuang.common.user;

/**
 * Protobuf type {@code UserReply}
 */
public final class UserReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserReply)
    UserReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserReply.newBuilder() to construct.
  private UserReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserReply() {
    msg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserReply();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.luckykuang.common.user.UserProto.internal_static_UserReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.luckykuang.common.user.UserProto.internal_static_UserReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.luckykuang.common.user.UserReply.class, com.luckykuang.common.user.UserReply.Builder.class);
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserReply.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.UserPb userPb = 1;</code>
     * @return Whether the userPb field is set.
     */
    boolean hasUserPb();
    /**
     * <code>.UserPb userPb = 1;</code>
     * @return The userPb.
     */
    com.luckykuang.common.user.UserPb getUserPb();
    /**
     * <code>.UserPb userPb = 1;</code>
     */
    com.luckykuang.common.user.UserPbOrBuilder getUserPbOrBuilder();
  }
  /**
   * Protobuf type {@code UserReply.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserReply.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Data();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luckykuang.common.user.UserProto.internal_static_UserReply_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luckykuang.common.user.UserProto.internal_static_UserReply_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luckykuang.common.user.UserReply.Data.class, com.luckykuang.common.user.UserReply.Data.Builder.class);
    }

    public static final int USERPB_FIELD_NUMBER = 1;
    private com.luckykuang.common.user.UserPb userPb_;
    /**
     * <code>.UserPb userPb = 1;</code>
     * @return Whether the userPb field is set.
     */
    @java.lang.Override
    public boolean hasUserPb() {
      return userPb_ != null;
    }
    /**
     * <code>.UserPb userPb = 1;</code>
     * @return The userPb.
     */
    @java.lang.Override
    public com.luckykuang.common.user.UserPb getUserPb() {
      return userPb_ == null ? com.luckykuang.common.user.UserPb.getDefaultInstance() : userPb_;
    }
    /**
     * <code>.UserPb userPb = 1;</code>
     */
    @java.lang.Override
    public com.luckykuang.common.user.UserPbOrBuilder getUserPbOrBuilder() {
      return userPb_ == null ? com.luckykuang.common.user.UserPb.getDefaultInstance() : userPb_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userPb_ != null) {
        output.writeMessage(1, getUserPb());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userPb_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUserPb());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.luckykuang.common.user.UserReply.Data)) {
        return super.equals(obj);
      }
      com.luckykuang.common.user.UserReply.Data other = (com.luckykuang.common.user.UserReply.Data) obj;

      if (hasUserPb() != other.hasUserPb()) return false;
      if (hasUserPb()) {
        if (!getUserPb()
            .equals(other.getUserPb())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserPb()) {
        hash = (37 * hash) + USERPB_FIELD_NUMBER;
        hash = (53 * hash) + getUserPb().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.luckykuang.common.user.UserReply.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luckykuang.common.user.UserReply.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luckykuang.common.user.UserReply.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luckykuang.common.user.UserReply.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luckykuang.common.user.UserReply.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luckykuang.common.user.UserReply.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luckykuang.common.user.UserReply.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luckykuang.common.user.UserReply.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luckykuang.common.user.UserReply.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.luckykuang.common.user.UserReply.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luckykuang.common.user.UserReply.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luckykuang.common.user.UserReply.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.luckykuang.common.user.UserReply.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserReply.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserReply.Data)
        com.luckykuang.common.user.UserReply.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luckykuang.common.user.UserProto.internal_static_UserReply_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luckykuang.common.user.UserProto.internal_static_UserReply_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luckykuang.common.user.UserReply.Data.class, com.luckykuang.common.user.UserReply.Data.Builder.class);
      }

      // Construct using com.luckykuang.common.user.UserReply.Data.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userPb_ = null;
        if (userPbBuilder_ != null) {
          userPbBuilder_.dispose();
          userPbBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luckykuang.common.user.UserProto.internal_static_UserReply_Data_descriptor;
      }

      @java.lang.Override
      public com.luckykuang.common.user.UserReply.Data getDefaultInstanceForType() {
        return com.luckykuang.common.user.UserReply.Data.getDefaultInstance();
      }

      @java.lang.Override
      public com.luckykuang.common.user.UserReply.Data build() {
        com.luckykuang.common.user.UserReply.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.luckykuang.common.user.UserReply.Data buildPartial() {
        com.luckykuang.common.user.UserReply.Data result = new com.luckykuang.common.user.UserReply.Data(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.luckykuang.common.user.UserReply.Data result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userPb_ = userPbBuilder_ == null
              ? userPb_
              : userPbBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luckykuang.common.user.UserReply.Data) {
          return mergeFrom((com.luckykuang.common.user.UserReply.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luckykuang.common.user.UserReply.Data other) {
        if (other == com.luckykuang.common.user.UserReply.Data.getDefaultInstance()) return this;
        if (other.hasUserPb()) {
          mergeUserPb(other.getUserPb());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getUserPbFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.luckykuang.common.user.UserPb userPb_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.luckykuang.common.user.UserPb, com.luckykuang.common.user.UserPb.Builder, com.luckykuang.common.user.UserPbOrBuilder> userPbBuilder_;
      /**
       * <code>.UserPb userPb = 1;</code>
       * @return Whether the userPb field is set.
       */
      public boolean hasUserPb() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       * @return The userPb.
       */
      public com.luckykuang.common.user.UserPb getUserPb() {
        if (userPbBuilder_ == null) {
          return userPb_ == null ? com.luckykuang.common.user.UserPb.getDefaultInstance() : userPb_;
        } else {
          return userPbBuilder_.getMessage();
        }
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public Builder setUserPb(com.luckykuang.common.user.UserPb value) {
        if (userPbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userPb_ = value;
        } else {
          userPbBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public Builder setUserPb(
          com.luckykuang.common.user.UserPb.Builder builderForValue) {
        if (userPbBuilder_ == null) {
          userPb_ = builderForValue.build();
        } else {
          userPbBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public Builder mergeUserPb(com.luckykuang.common.user.UserPb value) {
        if (userPbBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            userPb_ != null &&
            userPb_ != com.luckykuang.common.user.UserPb.getDefaultInstance()) {
            getUserPbBuilder().mergeFrom(value);
          } else {
            userPb_ = value;
          }
        } else {
          userPbBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public Builder clearUserPb() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userPb_ = null;
        if (userPbBuilder_ != null) {
          userPbBuilder_.dispose();
          userPbBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public com.luckykuang.common.user.UserPb.Builder getUserPbBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserPbFieldBuilder().getBuilder();
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public com.luckykuang.common.user.UserPbOrBuilder getUserPbOrBuilder() {
        if (userPbBuilder_ != null) {
          return userPbBuilder_.getMessageOrBuilder();
        } else {
          return userPb_ == null ?
              com.luckykuang.common.user.UserPb.getDefaultInstance() : userPb_;
        }
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.luckykuang.common.user.UserPb, com.luckykuang.common.user.UserPb.Builder, com.luckykuang.common.user.UserPbOrBuilder> 
          getUserPbFieldBuilder() {
        if (userPbBuilder_ == null) {
          userPbBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.luckykuang.common.user.UserPb, com.luckykuang.common.user.UserPb.Builder, com.luckykuang.common.user.UserPbOrBuilder>(
                  getUserPb(),
                  getParentForChildren(),
                  isClean());
          userPb_ = null;
        }
        return userPbBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserReply.Data)
    }

    // @@protoc_insertion_point(class_scope:UserReply.Data)
    private static final com.luckykuang.common.user.UserReply.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.luckykuang.common.user.UserReply.Data();
    }

    public static com.luckykuang.common.user.UserReply.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @java.lang.Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.luckykuang.common.user.UserReply.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_ = 0;
  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  public static final int MSG_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msg_ = "";
  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  @java.lang.Override
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUCCESS_FIELD_NUMBER = 3;
  private boolean success_ = false;
  /**
   * <code>bool success = 3;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int DATA_FIELD_NUMBER = 4;
  private com.luckykuang.common.user.UserReply.Data data_;
  /**
   * <code>.UserReply.Data data = 4;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.UserReply.Data data = 4;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.luckykuang.common.user.UserReply.Data getData() {
    return data_ == null ? com.luckykuang.common.user.UserReply.Data.getDefaultInstance() : data_;
  }
  /**
   * <code>.UserReply.Data data = 4;</code>
   */
  @java.lang.Override
  public com.luckykuang.common.user.UserReply.DataOrBuilder getDataOrBuilder() {
    return data_ == null ? com.luckykuang.common.user.UserReply.Data.getDefaultInstance() : data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
    }
    if (success_ != false) {
      output.writeBool(3, success_);
    }
    if (data_ != null) {
      output.writeMessage(4, getData());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, success_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getData());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.luckykuang.common.user.UserReply)) {
      return super.equals(obj);
    }
    com.luckykuang.common.user.UserReply other = (com.luckykuang.common.user.UserReply) obj;

    if (getCode()
        != other.getCode()) return false;
    if (!getMsg()
        .equals(other.getMsg())) return false;
    if (getSuccess()
        != other.getSuccess()) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.luckykuang.common.user.UserReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.luckykuang.common.user.UserReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.luckykuang.common.user.UserReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.luckykuang.common.user.UserReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.luckykuang.common.user.UserReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.luckykuang.common.user.UserReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.luckykuang.common.user.UserReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.luckykuang.common.user.UserReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.luckykuang.common.user.UserReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.luckykuang.common.user.UserReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.luckykuang.common.user.UserReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.luckykuang.common.user.UserReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.luckykuang.common.user.UserReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserReply)
      com.luckykuang.common.user.UserReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luckykuang.common.user.UserProto.internal_static_UserReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luckykuang.common.user.UserProto.internal_static_UserReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luckykuang.common.user.UserReply.class, com.luckykuang.common.user.UserReply.Builder.class);
    }

    // Construct using com.luckykuang.common.user.UserReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      code_ = 0;
      msg_ = "";
      success_ = false;
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.luckykuang.common.user.UserProto.internal_static_UserReply_descriptor;
    }

    @java.lang.Override
    public com.luckykuang.common.user.UserReply getDefaultInstanceForType() {
      return com.luckykuang.common.user.UserReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.luckykuang.common.user.UserReply build() {
      com.luckykuang.common.user.UserReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.luckykuang.common.user.UserReply buildPartial() {
      com.luckykuang.common.user.UserReply result = new com.luckykuang.common.user.UserReply(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.luckykuang.common.user.UserReply result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.msg_ = msg_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.success_ = success_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.data_ = dataBuilder_ == null
            ? data_
            : dataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.luckykuang.common.user.UserReply) {
        return mergeFrom((com.luckykuang.common.user.UserReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.luckykuang.common.user.UserReply other) {
      if (other == com.luckykuang.common.user.UserReply.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              code_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              msg_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              success_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {

      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {
      msg_ = getDefaultInstance().getMsg();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 2;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 3;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 3;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000004);
      success_ = false;
      onChanged();
      return this;
    }

    private com.luckykuang.common.user.UserReply.Data data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.luckykuang.common.user.UserReply.Data, com.luckykuang.common.user.UserReply.Data.Builder, com.luckykuang.common.user.UserReply.DataOrBuilder> dataBuilder_;
    /**
     * <code>.UserReply.Data data = 4;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     * @return The data.
     */
    public com.luckykuang.common.user.UserReply.Data getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.luckykuang.common.user.UserReply.Data.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public Builder setData(com.luckykuang.common.user.UserReply.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public Builder setData(
        com.luckykuang.common.user.UserReply.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public Builder mergeData(com.luckykuang.common.user.UserReply.Data value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          data_ != null &&
          data_ != com.luckykuang.common.user.UserReply.Data.getDefaultInstance()) {
          getDataBuilder().mergeFrom(value);
        } else {
          data_ = value;
        }
      } else {
        dataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000008);
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public com.luckykuang.common.user.UserReply.Data.Builder getDataBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public com.luckykuang.common.user.UserReply.DataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.luckykuang.common.user.UserReply.Data.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.luckykuang.common.user.UserReply.Data, com.luckykuang.common.user.UserReply.Data.Builder, com.luckykuang.common.user.UserReply.DataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.luckykuang.common.user.UserReply.Data, com.luckykuang.common.user.UserReply.Data.Builder, com.luckykuang.common.user.UserReply.DataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UserReply)
  }

  // @@protoc_insertion_point(class_scope:UserReply)
  private static final com.luckykuang.common.user.UserReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.luckykuang.common.user.UserReply();
  }

  public static com.luckykuang.common.user.UserReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserReply>
      PARSER = new com.google.protobuf.AbstractParser<UserReply>() {
    @java.lang.Override
    public UserReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.luckykuang.common.user.UserReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

