server:
  port: 9000

spring:
  application:
    name: gateway-server
  cloud:
    # 注册中心配置
    consul:
      host: 1.12.248.106 # 这里是consul服务端的地址
      port: 8500 # 这是consul服务端的端口
      discovery:
        health-check-timeout: 5s # 检测超时时间
        health-check-critical-timeout: 10s # 设置超时30秒之后，注销服务,这里数字要大于心跳检测的数字
        heartbeat:
          enabled: true
          ttl: 5 # 这里开启心跳检测，设置10s提交一次心跳，用于consul与服务不在同一个网段的情况，支持存活检测
        prefer-ip-address: true
        instance-group: default # 设置实例所在组
    # 网关配置
    gateway:
      # 跨域处理
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许跨域的url * 则允许全部
            allowed-origin-patterns: "*"
            # 允许跨域的方法 * 则全部
            allowed-methods: "*"
            # 允许跨域的请求头 * 则全部
            allowed-headers: "*"
            # 是否允许cookie跨域  true允许
            allow-credentials: true
      # 动态路由开关配置
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      # 路由配置
      routes:
        # openfeign 服务端
        - id: openfeign-server  # 路由的ID，没有固定规则，但要求唯一，建议配合服务名
          uri: lb://openfeign-server  # 匹配后提供服务的路由地址，动态路由格式统一为 lb://注册中心的服务名字
          predicates:
            - Path=/openfeign/server/**  # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=2  # 去除掉前面2个前缀之后，根据path的配置设置对应值
        # openfeign 客户端
        - id: openfeign-client  # 路由的ID，没有固定规则，但要求唯一，建议配合服务名
          uri: lb://openfeign-client  # 匹配后提供服务的路由地址，动态路由格式统一为 lb://注册中心的服务名字
          predicates:
            - Path=/openfeign/client/**  # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=2  # 去除掉前面2个前缀之后，根据path的配置设置对应值