server:
  port: 9001
spring:
  application:
    name: openfeign-server
  cloud:
    consul:
      host: 192.168.1.100 # 这里是consul服务端的地址
      port: 8500 # 这是consul服务端的端口
      discovery:
        health-check-timeout: 5s # 检测超时时间
        health-check-critical-timeout: 10s # 设置超时30秒之后，注销服务,这里数字要大于心跳检测的数字
        heartbeat:
          enabled: true
          ttl: 5 # 这里开启心跳检测，设置10s提交一次心跳，用于consul与服务不在同一个网段的情况，支持存活检测
        prefer-ip-address: true
        instance-group: default # 设置实例所在组