server:
  port: 9011
spring:
  application:
    name: sentinel-server
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?refresh=true
  cloud:
    nacos:
      config:
        # Nacos 配置中心的namespace。需要注意，如果使用 public 的 namcespace ，请不要填写这个值，直接留空即可
        namespace: sentinel
        server-addr: localhost:8848 # 10.10.18.16:8848,10.10.18.16:2848,10.10.18.16:5848
        username: nacos
        password: nacos
        file-extension: yml
        group: SENTINEL_GROUP
      discovery:
        namespace: sentinel
        server-addr: localhost:8848 # 10.10.18.16:8848,10.10.18.16:2848,10.10.18.16:5848
        username: nacos
        password: nacos
        group: SENTINEL_GROUP
    sentinel:
      transport:
        # Sentinel DashBoard的地址
        dashboard: localhost:8080 # 10.10.22.174:8109
        # Sentinel与控制台交互的端口
        port: 8719
#        clientIp: localhost
      #服务启动后直接与sentinel建立心跳连接
      eager: true
#      datasource:
#        # 名称随意
#        flow:
#          nacos:
#            server-addr: localhost:8848 # 10.10.18.16:8848,10.10.18.16:2848,10.10.18.16:5848
#            username: nacos
#            password: nacos
#            # nacos连接的分组
#            groupId: SENTINEL_GROUP
#            dataId: ${spring.application.name}-flow-rules
#            data-type: json
#            rule-type: flow
#        degrade:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-degrade-rules
#            groupId: SENTINEL_GROUP
#            rule-type: degrade
#            data-type: json
#            username: nacos
#            password: nacos
#        system:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-system-rules
#            groupId: SENTINEL_GROUP
#            rule-type: system
#            data-type: json
#            username: nacos
#            password: nacos
#        authority:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-authority-rules
#            groupId: SENTINEL_GROUP
#            rule-type: authority
#            data-type: json
#            username: nacos
#            password: nacos
#        param-flow:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-param-flow-rules
#            groupId: SENTINEL_GROUP
#            rule-type: param-flow
#            data-type: json
#            username: nacos
#            password: nacos

# 开启sentinel
feign:
  sentinel:
    enabled: true