server:
  port: 9099
spring:
  application:
    name: redis
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      host: 192.168.1.100
      port: 6379
      password: ''
      ssl:
        enabled: false
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0