tcp:
  # tcp server 端口
  port: 9030
  # tcp server 编码 十进制：ascii 十六进制：hex
  codec: ascii
  # 通道没接收消息，默认0禁用
  readerIdleTime: 15
  # 通道没发送消息，默认0禁用
  writerIdleTime: 0
  # 通道没有接收/发送消息，默认0禁用
  allIdleTime: 0

spring:
  application:
    name: netty-tcp-server