server:
  port: 9010
spring:
  application:
    name: sentinel-client
  config:
    # nacos:nacos-config-example.properties?refresh=true
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?refresh=true
  cloud:
    nacos:
      config:
        # Nacos 配置中心的namespace。需要注意，如果使用 public 的 namcespace ，请不要填写这个值，直接留空即可
        # spring.cloud.nacos.config.namespace=
        namespace: sentinel
        server-addr: localhost:8848 # 10.10.18.16:8848,10.10.18.16:2848,10.10.18.16:5848
        username: nacos
        password: nacos
        file-extension: yml
        group: SENTINEL_GROUP
      discovery:
        namespace: sentinel
        server-addr: localhost:8848 # 10.10.18.16:8848,10.10.18.16:2848,10.10.18.16:5848
        username: nacos
        password: nacos
        group: SENTINEL_GROUP
    sentinel:
      transport:
        # Sentinel DashBoard的地址
        dashboard: localhost:8080 # 10.10.22.174:8109
        # Sentinel与控制台交互的端口
        port: 8719
      #服务启动后直接与sentinel建立心跳连接
      eager: true
      datasource:
        # 名称随意
        flow:
          nacos:
            # nacos连接地址
            server-addr: localhost:8848 # 10.10.18.16:8848,10.10.18.16:2848,10.10.18.16:5848
            username: nacos
            password: nacos
            namespace: sentinel
            # nacos连接的分组
            groupId: SENTINEL_GROUP
            # 读取配置文件的名称
            dataId: ${spring.application.name}-flow-rules
            # 规则类型:flow(流控)，degrade(熔断)，param-flow(热点)，authority(授权)
            rule-type: flow
            # 读取配置文件的后缀
            data-type: json
        degrade:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            namespace: sentinel
            groupId: SENTINEL_GROUP
            dataId: ${spring.application.name}-degrade-rules
            rule-type: degrade
            data-type: json
        param-flow:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            namespace: sentinel
            groupId: SENTINEL_GROUP
            dataId: ${spring.application.name}-param-flow-rules
            rule-type: param-flow
            data-type: json
        authority:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            namespace: sentinel
            groupId: SENTINEL_GROUP
            dataId: ${spring.application.name}-authority-rules
            rule-type: authority
            data-type: json

#开启sentinel
feign:
  sentinel:
    enabled: true